<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <AssemblyName>MikroPanelScannerAgentSetup</AssemblyName>
    <RootNamespace>MikroPanelScannerAgentSetup</RootNamespace>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource
      Include="../windows/MikroPanelScannerAgent.ps1"
      Link="MikroPanelScannerAgent.ps1"
      LogicalName="MikroPanelScannerAgent.ps1"
    />
  </ItemGroup>

</Project>
